name: graph_svd
channels:
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - appnope=0.1.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - blosc=1.21.3
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.05.30
  - certifi=2023.7.22
  - cffi=1.15.1
  - cfitsio=3.470
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cloudpickle=2.2.1
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=41.0.2
  - cycler=0.11.0
  - cytoolz=0.12.0
  - dask-core=2023.6.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=0.8.3
  - fonttools=4.25.0
  - freetype=2.12.1
  - fsspec=2023.4.0
  - giflib=5.2.1
  - gmp=6.2.1
  - idna=3.4
  - imagecodecs=2021.8.26
  - imageio=2.31.1
  - importlib-metadata=6.0.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - jupyterlab_widgets=3.0.5
  - jxrlib=1.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy_loader=0.2
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.4
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.1.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - llvm-openmp=14.0.6
  - locket=1.0.0
  - lz4-c=1.9.4
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - metis=5.1.1
  - mpfr=4.2.0
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - numexpr=2.8.4
  - numpy=1.25.0
  - numpy-base=1.25.0
  - openjpeg=2.3.0
  - openssl=3.1.1
  - packaging=23.0
  - pandas=1.5.3
  - parso=0.8.3
  - partd=1.2.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.2.1
  - platformdirs=2.5.2
  - pooch=1.4.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.4
  - python-dateutil=2.8.2
  - python_abi=3.11
  - pytz=2022.7
  - pywavelets=1.4.1
  - pyyaml=6.0
  - pyzmq=25.1.0
  - readline=8.2
  - requests=2.31.0
  - scikit-image=0.20.0
  - scikit-learn=1.2.2
  - scikit-sparse=0.4.12
  - scipy=1.10.1
  - seaborn=0.12.2
  - setuptools=68.0.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.41.2
  - stack_data=0.2.0
  - suitesparse=5.10.1
  - tbb=2020.2
  - threadpoolctl=2.2.0
  - tifffile=2021.7.2
  - tk=8.6.12
  - toolz=0.12.0
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - tzdata=2023c
  - urllib3=1.26.16
  - wcwidth=0.2.5
  - wheel=0.38.4
  - widgetsnbextension=4.0.5
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
prefix: /opt/homebrew/anaconda3/envs/graph_svd
